#!/usr/bin/env python3

# -*- mode: python -*-

import os, sys
import logging

from modules import cloudmap, grv, utils
from modules import paramStore

def main():
    if os.environ.get('GALAGA_VERBOSE'):
        logging.basicConfig(level=logging.INFO)

    if utils.check_dryrun(os.path.basename(__file__)):
        sys.exit(0)

    arcade_name = os.environ.get('GALAGA_ARCADE_NAME')

    if not arcade_name:
        print("Invalid arcade name")
        sys.exit(1)

    #vpc_id = grv.get_vpc_id(arcade_name)

    #status = cloudmap.create_cloudmap_namespace(vpc_id, arcade_name)
    if status:
        sys.exit(0)
    else:
        logging.error(status)
        sys.exit(1)


if __name__ == '__main__':
    main()
