#!/usr/bin/env python3

# -*- mode: python -*-

import logging
import os, sys

from modules import cloudmap
from modules.utils import print_status


def main():
    if os.environ.get('GALAGA_VERBOSE'):
        logging.basicConfig(level=logging.INFO)

    arcade_name = os.environ.get('GALAGA_ARCADE_NAME')

    if not arcade_name:
        print("Invalid arcade name")
        sys.exit(1)

    #cloudmap_status = cloudmap.get_cloudmap_status(arcade_name)

    if cloudmap_status:
        print_status(cloudmap_status)
        sys.exit(0)
    else:
        sys.exit(1)


if __name__ == '__main__':
    main()
